### ISSUE TITLE
1.7.10 Kcauldron - CommandWhitelist-1.7.3

### ISSUE THREAD

**Issue by twixi** [YouHaveTrouble/CommandWhitelist#23]
[00:23:26 WARN]: org.apache.commons.lang.UnhandledException: Plugin CommandWhitelist v1.7.3 generated an exception while executing task 3944
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.updateCommands()V
        at eu.endermite.commandwhitelist.spigot.CommandWhitelist.lambda$reloadPluginConfig$0(CommandWhitelist.java:68)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by YouHaveTrouble** [comment]
seems like you're trying to use CW on  minecraft 1.7, which is unsupported.
