### ISSUE TITLE
When i do the command for add a command i get this error on console.

### ISSUE THREAD

**Issue by Frank21333** [YouHaveTrouble/CommandWhitelist#35]
```
[20:34:55 INFO]: CENSORED issued server command: /cw add default worldguard
[20:34:55 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cw' in plugin CommandWhitelist v1.7.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_282]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.updateCommands()V
        at eu.endermite.commandwhitelist.spigot.config.ConfigCache.addCommand(ConfigCache.java:65) ~[?:?]
        at eu.endermite.commandwhitelist.spigot.command.MainCommand.onCommand(MainCommand.java:33) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-db6de12-18fbb24]
        ... 15 more
```
![image](https://user-images.githubusercontent.com/71409554/130285225-5a5a53ef-bb4a-47c9-81c8-274a5db89708.png)

**Comment by YouHaveTrouble** [comment]
One of the multiple reasons why 1.8 is not supported anymore. Try older plugin version.

**Comment by Frank21333** [comment]
ok, i can try

**Comment by Frank21333** [comment]
what version i can use in 1.8.8?

**Comment by Frank21333** [comment]
1.7.3 not working. Same error
