### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Sohqil** [YouHaveTrouble/CommandWhitelist#46]
Console Error

[19:57:26] [Server thread/INFO]: [CommandWhitelist] Enabling CommandWhitelist v2.2.1
[19:57:26] [Server thread/ERROR]: Error occurred while enabling CommandWhitelist v2.2.1 (Is it up to date?)
java.lang.NoSuchMethodError: eu.endermite.commandwhitelist.bukkit.CommandWhitelistBukkit.getSLF4JLogger()Lorg/slf4j/Logger;
	at eu.endermite.commandwhitelist.bukkit.CommandWhitelistBukkit.reloadPluginConfig(CommandWhitelistBukkit.java:71) ~[?:?]
	at eu.endermite.commandwhitelist.bukkit.CommandWhitelistBukkit.onEnable(CommandWhitelistBukkit.java:38) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
[19:57:26] [Server thread/INFO]: [CommandWhitelist] Disabling CommandWhitelist v2.2.1

**Server Version**
1.8.8 PaperSpigot
Using latest version of plugin (v2.2.1)

**Comment by YouHaveTrouble** [comment]
2.x version of the plugin only supports versions 1.13 and above.
