### ISSUE TITLE
MC Server not working

### ISSUE THREAD

**Issue by SebbyIsSwag** [YouHaveTrouble/CommandWhitelist#53]
I know this doesn't really fit here but my servers not working on boot up this is my latest.log
[13:29:14] [Server thread/ERROR]: Encountered an unexpected exception
com.google.gson.JsonSyntaxException: Expected entry to be a JsonObject, was "Sebby"
	at afd.m(SourceFile:393) ~[minecraft_server.1.16.5.jar:?]
	at acy.f(SourceFile:122) ~[minecraft_server.1.16.5.jar:?]
	at zf.y(SourceFile:95) ~[minecraft_server.1.16.5.jar:?]
	at zf.<init>(SourceFile:22) ~[minecraft_server.1.16.5.jar:?]
	at zg.d(SourceFile:169) ~[minecraft_server.1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.w(SourceFile:645) ~[minecraft_server.1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:257) ~[minecraft_server.1.16.5.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[13:29:14] [Server thread/ERROR]: This crash report has been saved to: D:\Uploads\damnserver 2\minecraft\.\crash-reports\crash-2022-07-06_13.29.14-server.txt
[13:29:14] [Server thread/INFO]: Stopping server
[13:29:14] [Server thread/INFO]: Saving worlds
[13:29:14] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "aag.f()" because "?" is null
	at net.minecraft.server.MinecraftServer.a(SourceFile:572) ~[minecraft_server.1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.t(SourceFile:599) ~[minecraft_server.1.16.5.jar:?]
	at zg.t(SourceFile:567) ~[minecraft_server.1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.w(SourceFile:707) ~[minecraft_server.1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:257) ~[minecraft_server.1.16.5.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by YouHaveTrouble** [comment]
Error you're getting means json file parsing failed somewhere where the input provided was "Sebby" instead. Not related to CW at all since it doesn't parse json at all.
Log sends you to a crash report, that will probably provide more information ;)

**Comment by SebbyIsSwag** [comment]
### so uh this is my crash report
`` ---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 06/07/2022, 11:09
Description: Watching Server

java.lang.Error: Watchdog
	at java.base@16/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base@16/java.io.FileOutputStream.write(FileOutputStream.java:347)
	at java.base@16/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base@16/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base@16/java.io.PrintStream.write(PrintStream.java:570)
	at app//org.apache.logging.log4j.core.util.CloseShieldOutputStream.write(CloseShieldOutputStream.java:53)
	at app//org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:256)
	at app//org.apache.logging.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:288)
	at app//org.apache.logging.log4j.core.appender.OutputStreamManager.flush(OutputStreamManager.java:297)
	at app//org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:179)
	at app//org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170)
	at app//org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161)
	at app//org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at app//org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at app//org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at app//org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at app//org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
	at app//org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
	at app//org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
	at app//org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
	at app//org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at app//org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at app//org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091)
	at app//org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2011)
	at app//org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1884)
	at app//org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1426)
	at app//aay.a(SourceFile:1112)
	at app//nd.m(SourceFile:396)
	at app//aax.c(SourceFile:186)
	at app//net.minecraft.server.MinecraftServer.b(SourceFile:882)
	at app//zg.b(SourceFile:312)
	at app//net.minecraft.server.MinecraftServer.a(SourceFile:811)
	at app//net.minecraft.server.MinecraftServer.w(SourceFile:670)
	at app//net.minecraft.server.MinecraftServer.a(SourceFile:257)
	at app//net.minecraft.server.MinecraftServer$$Lambda$3442/0x00000008012a6cc0.run(Unknown Source)
	at java.base@16/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at java.base@16/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base@16/java.io.FileOutputStream.write(FileOutputStream.java:347)
	at java.base@16/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base@16/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base@16/java.io.PrintStream.write(PrintStream.java:570)
	at app//org.apache.logging.log4j.core.util.CloseShieldOutputStream.write(CloseShieldOutputStream.java:53)
	at app//org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:256)
	at app//org.apache.logging.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:288)
	at app//org.apache.logging.log4j.core.appender.OutputStreamManager.flush(OutputStreamManager.java:297)
	at app//org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:179)
	at app//org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170)
	at app//org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161)
	at app//org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at app//org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at app//org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at app//org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at app//org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
	at app//org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
	at app//org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
	at app//org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
	at app//org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at app//org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at app//org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091)
	at app//org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2011)
	at app//org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1884)
	at app//org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1426)
	at app//aay.a(SourceFile:1112)
	at app//nd.m(SourceFile:396)
	at app//aax.c(SourceFile:186)
	at app//net.minecraft.server.MinecraftServer.b(SourceFile:882)
	at app//zg.b(SourceFile:312)
	at app//net.minecraft.server.MinecraftServer.a(SourceFile:811)
	at app//net.minecraft.server.MinecraftServer.w(SourceFile:670)
	at app//net.minecraft.server.MinecraftServer.a(SourceFile:257)

-- Thread Dump --
Details:
	Threads: "Reference Handler" daemon prio=10 Id=2 RUNNABLE
	at java.base@16/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
	at java.base@16/java.lang.ref.Reference.processPendingReferences(Reference.java:243)
	at java.base@16/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)


"Finalizer" daemon prio=8 Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@79381541
	at java.base@16/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@79381541
	at java.base@16/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@16/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
	at java.base@16/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:171)


"Signal Dispatcher" daemon prio=9 Id=4 RUNNABLE


"Attach Listener" daemon prio=5 Id=5 RUNNABLE


"Notification Thread" daemon prio=9 Id=21 RUNNABLE


"Common-Cleaner" daemon prio=8 Id=22 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@77fff416
	at java.base@16/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@77fff416
	at java.base@16/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@16/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
	at java.base@16/java.lang.Thread.run(Thread.java:831)
	at java.base@16/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)


"Worker-Bootstrap-4" daemon prio=5 Id=29 WAITING on java.util.concurrent.ForkJoinPool@73c07e31
	at java.base@16/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@73c07e31
	at java.base@16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1633)
	at java.base@16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


"Timer hack thread" daemon prio=5 Id=33 TIMED_WAITING
	at java.base@16/java.lang.Thread.sleep(Native Method)
	at app//x$6.run(SourceFile:636)


"Worker-Main-8" daemon prio=5 Id=34 WAITING on java.util.concurrent.ForkJoinPool@36c2fe2d
	at java.base@16/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@36c2fe2d
	at java.base@16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1633)
	at java.base@16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


"Worker-Main-11" daemon prio=5 Id=37 WAITING on java.util.concurrent.ForkJoinPool@36c2fe2d
	at java.base@16/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@36c2fe2d
	at java.base@16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1633)
	at java.base@16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


"Worker-Main-13" daemon prio=5 Id=39 WAITING on java.util.concurrent.ForkJoinPool@36c2fe2d
	at java.base@16/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@36c2fe2d
	at java.base@16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1633)
	at java.base@16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


"Snooper Timer" daemon prio=5 Id=42 WAITING on java.util.TaskQueue@f6977a9
	at java.base@16/java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@f6977a9
	at java.base@16/java.lang.Object.wait(Object.java:320)
	at java.base@16/java.util.TimerThread.mainLoop(Timer.java:527)
	at java.base@16/java.util.TimerThread.run(Timer.java:506)


"Java2D Disposer" daemon prio=10 Id=43 WAITING on java.lang.ref.ReferenceQueue$Lock@7be6d16
	at java.base@16/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@7be6d16
	at java.base@16/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@16/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
	at java.desktop@16/sun.java2d.Disposer.run(Disposer.java:144)
	at java.base@16/java.lang.Thread.run(Thread.java:831)


"AWT-Shutdown" prio=5 Id=44 WAITING on java.lang.Object@77ffba26
	at java.base@16/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@77ffba26
	at java.base@16/java.lang.Object.wait(Object.java:320)
	at java.desktop@16/sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:291)
	at java.base@16/java.lang.Thread.run(Thread.java:831)


"AWT-Windows" daemon prio=6 Id=45 RUNNABLE (in native)
	at java.desktop@16/sun.awt.windows.WToolkit.eventLoop(Native Method)
	at java.desktop@16/sun.awt.windows.WToolkit.run(WToolkit.java:361)
	at java.base@16/java.lang.Thread.run(Thread.java:831)


"AWT-EventQueue-0" prio=6 Id=47 RUNNABLE
	at java.base@16/sun.util.logging.PlatformLogger.isLoggable(PlatformLogger.java:340)
	at java.desktop@16/java.awt.Component.isMixingNeeded(Component.java:10420)
	at java.desktop@16/java.awt.Container.mixOnReshaping(Container.java:4342)
	-  locked java.awt.Component$AWTTreeLock@56ed0162
	at java.desktop@16/java.awt.Component.reshape(Component.java:2368)
	-  locked java.awt.Component$AWTTreeLock@56ed0162
	at java.desktop@16/javax.swing.JComponent.reshape(JComponent.java:4250)
	at java.desktop@16/java.awt.Component.setBounds(Component.java:2330)
	at java.desktop@16/java.awt.Component.resize(Component.java:2246)
	-  locked java.awt.Component$AWTTreeLock@56ed0162
	at java.desktop@16/java.awt.Component.setSize(Component.java:2231)
	...


"TimerQueue" daemon prio=5 Id=49 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@66dfe9ad
	at java.base@16/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@66dfe9ad
	at java.base@16/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at java.base@16/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1661)
	at java.base@16/java.util.concurrent.DelayQueue.take(DelayQueue.java:229)
	at java.desktop@16/javax.swing.TimerQueue.run(TimerQueue.java:171)
	at java.base@16/java.lang.Thread.run(Thread.java:831)

	Number of locked synchronizers = 1
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@127df029


"D3D Screen Updater" daemon prio=7 Id=51 TIMED_WAITING on java.lang.Object@6cfb51da
	at java.base@16/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@6cfb51da
	at java.desktop@16/sun.java2d.d3d.D3DScreenUpdateManager.run(D3DScreenUpdateManager.java:423)
	at java.base@16/java.lang.Thread.run(Thread.java:831)


"Thread-1" daemon prio=5 Id=48 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@52a3bb36
	at java.base@16/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@52a3bb36
	at java.base@16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
	at java.base@16/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:505)
	at java.base@16/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3137)
	at java.base@16/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1614)
	at java.base@16/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
	at app//com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:77)
	at app//zm.a(SourceFile:137)
	...


"Server thread" prio=5 Id=41 RUNNABLE
	at java.base@16/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base@16/java.io.FileOutputStream.write(FileOutputStream.java:347)
	at java.base@16/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base@16/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	-  locked java.io.BufferedOutputStream@2f22f5f3
	at java.base@16/java.io.PrintStream.write(PrintStream.java:570)
	-  locked java.io.PrintStream@36a9e33b
	at app//org.apache.logging.log4j.core.util.CloseShieldOutputStream.write(CloseShieldOutputStream.java:53)
	at app//org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:256)
	-  locked org.apache.logging.log4j.core.appender.OutputStreamManager@ea11b5
	at app//org.apache.logging.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:288)
	-  locked org.apache.logging.log4j.core.appender.OutputStreamManager@ea11b5
	...


"DestroyJavaVM" prio=5 Id=53 RUNNABLE


"Server console handler" daemon prio=5 Id=54 RUNNABLE (in native)
	at java.base@16/java.io.FileInputStream.readBytes(Native Method)
	at java.base@16/java.io.FileInputStream.read(FileInputStream.java:271)
	at java.base@16/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
	at java.base@16/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	-  locked java.io.BufferedInputStream@776a89f0
	at java.base@16/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:297)
	at java.base@16/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at java.base@16/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	-  locked java.io.InputStreamReader@ea30c1d
	at java.base@16/java.io.InputStreamReader.read(InputStreamReader.java:178)
	...


"ObjectCleanerThread" daemon prio=1 Id=55 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@5e94d3c5
	at java.base@16/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@5e94d3c5
	at java.base@16/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at app//io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@16/java.lang.Thread.run(Thread.java:831)


"Netty Server IO #0" daemon prio=5 Id=56 RUNNABLE (in native)
	at java.base@16/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at java.base@16/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:353)
	at java.base@16/sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:178)
	at java.base@16/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
	-  locked sun.nio.ch.Util$2@6afbcb4a
	-  locked sun.nio.ch.WindowsSelectorImpl@49fdfaec
	at java.base@16/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:141)
	at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	...


"Server Watchdog" daemon prio=5 Id=60 RUNNABLE
	at java.management@16/sun.management.ThreadImpl.dumpThreads0(Native Method)
	at java.management@16/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
	at java.management@16/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
	at app//zj.run(SourceFile:49)
	at java.base@16/java.lang.Thread.run(Thread.java:831)


"Netty Server IO #1" daemon prio=5 Id=61 RUNNABLE (in native)
	at java.base@16/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at java.base@16/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:353)
	at java.base@16/sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:178)
	at java.base@16/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
	-  locked sun.nio.ch.Util$2@5f28c42a
	-  locked sun.nio.ch.WindowsSelectorImpl@27da2ef1
	at java.base@16/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:141)
	at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	...


"Netty Server IO #2" daemon prio=5 Id=62 RUNNABLE
	at java.base@16/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at java.base@16/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:353)
	at java.base@16/sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:178)
	at java.base@16/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
	-  locked sun.nio.ch.Util$2@134f10db
	-  locked sun.nio.ch.WindowsSelectorImpl@3543a2c4
	at java.base@16/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:141)
	at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	...


"Worker-Main-18" daemon prio=5 Id=66 WAITING on java.util.concurrent.ForkJoinPool@36c2fe2d
	at java.base@16/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@36c2fe2d
	at java.base@16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1633)
	at java.base@16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


"Worker-Main-19" daemon prio=5 Id=67 WAITING on java.util.concurrent.ForkJoinPool@36c2fe2d
	at java.base@16/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@36c2fe2d
	at java.base@16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1633)
	at java.base@16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


"Worker-Main-34" daemon prio=5 Id=82 TIMED_WAITING on java.util.concurrent.ForkJoinPool@36c2fe2d
	at java.base@16/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@36c2fe2d
	at java.base@16/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:293)
	at java.base@16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1624)
	at java.base@16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


"Netty Server IO #3" daemon prio=5 Id=84 RUNNABLE (in native)
	at java.base@16/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at java.base@16/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:353)
	at java.base@16/sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:178)
	at java.base@16/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
	-  locked sun.nio.ch.Util$2@2cd339d2
	-  locked sun.nio.ch.WindowsSelectorImpl@5a88271f
	at java.base@16/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:141)
	at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	...



Stacktrace:
	at zj.run(SourceFile:65)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- Performance stats --
Details:
	Random tick rate: 3
	Level stats: ResourceKey[minecraft:dimension / minecraft:overworld]: players: 0, entities: 335 [minecraft:item:61,minecraft:chicken:40,minecraft:sheep:30,minecraft:pig:29,minecraft:zombie:25], block_entities: 44 [minecraft:mob_spawner:24,minecraft:chest:18,minecraft:beehive:2], block_ticks: 1359, fluid_ticks: 31, chunk_source: ServerChunkCache: 2202,
ResourceKey[minecraft:dimension / minecraft:the_nether]: players: 0, entities: 0 [], block_entities: 0 [], block_ticks: 0, fluid_ticks: 0, chunk_source: ServerChunkCache: 0,
ResourceKey[minecraft:dimension / minecraft:the_end]: players: 0, entities: 0 [], block_entities: 0 [], block_ticks: 0, fluid_ticks: 0, chunk_source: ServerChunkCache: 0

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1518935192 bytes (1448 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 2 total; -Xmx2048M -Xms2048M
	Player Count: 0 / 20; []
	Data Packs: vanilla
	Is Modded: Unknown (can't tell)
	Type: Dedicated Server (map_server.txt)

**Comment by YouHaveTrouble** [comment]
From what I can tell it's really just the fact that you put some text where there should be json, try regenerating all your .json files and server.properties

**Comment by SebbyIsSwag** [comment]
### I followed your advise and it worked! further info for me or some other stuff, just reply
